In [87]:
import numpy as np
import scipy as sp
from scipy import linalg

In [88]:
matriz_A = np.array([[1,2,3],[3,2,1],[5,6,4]])
matriz_B = np.array([[3,2],[2,1],[5,7]])

print(f"Matriz A: \n{matriz_A} \n \n Matriz B: \n{matriz_B}")

Matriz A: 
[[1 2 3]
 [3 2 1]
 [5 6 4]] 
 
 Matriz B: 
[[3 2]
 [2 1]
 [5 7]]


Equação linear em forma matricial

A(matriz).x(vetor) = b \
A - matriz dos coeficientes \
x - vetor das incógnitas \
b - vetor das constantes

In [89]:
matriz = np.array([[1,2,3],[2,-1,1],[-2,-3,3]])
matriz

array([[ 1,  2,  3],
       [ 2, -1,  1],
       [-2, -3,  3]])

In [90]:
# vetor das constantes
vetor = np.array([2,-1,-11])
vetor

array([  2,  -1, -11])

In [91]:
np.array([matriz[:,0],matriz[:,1],matriz[:,2]])

array([[ 1,  2, -2],
       [ 2, -1, -3],
       [ 3,  1,  3]])

In [92]:
np.array([matriz[:,0],matriz[:,1],matriz[:,2]]).T

array([[ 1,  2,  3],
       [ 2, -1,  1],
       [-2, -3,  3]])

In [107]:
def cramer3(A,b):
    det = sp.linalg.det(np.array([A[:,0],A[:,1],A[:,2]]).T)
    
    if not np.isclose(det, 0, atol=1e-12):
        detx = sp.linalg.det(np.array([b[:],A[:,1],A[:,2]]).T)
        dety = sp.linalg.det(np.array([A[:,0],b[:],A[:,2]]).T)
        detz = sp.linalg.det(np.array([A[:,0],A[:,1],b[:]]).T)
        x = detx/det
        y = dety/det
        z = detz/det
        print('O valor de x é {:.2f}'.format (x))
        print('O valor de y é {:.2f}'.format (y))
        print('O valor de z é {:.2f}'.format (z))
    else:
        print('Determinante da matriz dos coeficientes é nula')   

In [94]:
cramer3(matriz,vetor)

O valor de x é 1.00
O valor de y é 2.00
O valor de z é -1.00


In [117]:
matriz2 = np.array([[3,2,7],
                   [4,-29,3],
                   [2,3,5]])
matriz2

array([[  3,   2,   7],
       [  4, -29,   3],
       [  2,   3,   5]])

In [113]:
vetor2 = np.array([1,2,2])
vetor2

array([1, 2, 2])

In [114]:
cramer3(matriz2,vetor2)

Determinante da matriz dos coeficientes é nula


In [115]:


determinante_M2 = sp.linalg.det(matriz2)
print(round(determinante_M2, 2))

0.0


In [116]:
determinante_M1 = sp.linalg.det(matriz)
print(determinante_M1)

-40.0


In [118]:
def cramer2 (A,b):
    det = sp.linalg.det(np.array([A[:,0],A[:,1]]).T)
    
    if not np.isclose(det, 0, atol=1e-12):
        detx = sp.linalg.det(np.array([b[:],A[:,1]]).T)
        dety = sp.linalg.det(np.array([A[:,0],b[:]]).T)
        x = detx/det
        y = dety/det
        print('O valor de x é {:.2f}'.format (x))
        print('O valor de y é {:.2f}'.format (y))
    else:
        print('Determinante da matriz dos coeficientes é nula')

In [121]:
matriz_c = np.array([[1,4],[2,3]])
vetor_c = np.array([200,180])

In [122]:
cramer2(matriz_c, vetor_c)


O valor de x é 24.00
O valor de y é 44.00
