In [27]:
import numpy as np


In [40]:
matriz = [[2, 3, 4],
          [1, 2, 2],
          [5, 3, 3]]


In [41]:
matriz1 = np.array(matriz)
matriz1

array([[2, 3, 4],
       [1, 2, 2],
       [5, 3, 3]])

In [42]:
matriz2 = np.array([[2,3,4], [3,3,2], [4,1,6]])
matriz2


array([[2, 3, 4],
       [3, 3, 2],
       [4, 1, 6]])

In [43]:
mult = np.dot(matriz1,matriz2)
print(mult)

[[29 19 38]
 [16 11 20]
 [31 27 44]]


In [44]:
inversa = np.linalg.inv(matriz1)
print(inversa)

[[ 0.00000000e+00 -4.28571429e-01  2.85714286e-01]
 [-1.00000000e+00  2.00000000e+00 -3.08395285e-17]
 [ 1.00000000e+00 -1.28571429e+00 -1.42857143e-01]]


In [53]:
inv = np.dot(matriz1, inversa)
print(inv)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
determinante = np.linalg.det(matriz2)
print(determinante)

-34.00000000000001


In [34]:
type(matriz1)

numpy.ndarray

In [35]:
matriz1.shape

(3, 3)

In [36]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
identidade = np.eye(3)
identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
teste = np.dot(inversa,identidade)
teste

array([[-0.57142857,  0.71428571,  0.28571429],
       [ 0.33333333, -0.66666667,  0.        ],
       [ 0.28571429,  0.14285714, -0.14285714]])

In [39]:
mat.shape

(3, 4)

In [49]:
import numpy as np

# Criando as estruturas
escalar = np.array(10)
vetor   = np.array([1, 2, 3])
matriz  = np.array([[1, 2, 3], [4, 5, 6]])

# Verificando os 'Shapes' (Formatos)
print(f"Escalar: {escalar.ndim} Dimensões | Shape: {escalar.shape}")
print(f"Vetor:   {vetor.ndim} Dimensão   | Shape: {vetor.shape}")
print(f"Matriz:  {matriz.ndim} Dimensões  | Shape: {matriz.shape}")

Escalar: 0 Dimensões | Shape: ()
Vetor:   1 Dimensão   | Shape: (3,)
Matriz:  2 Dimensões  | Shape: (2, 3)
