In [1]:
import numpy as np
import matplotlib.pyplot as plt

# AUTOVETOR E AUTOVALOR

In [2]:
A = np.array([[3,0],[0,1]])
A

array([[3, 0],
       [0, 1]])

In [3]:
autovalor, autovetor = np.linalg.eig(A)

In [4]:
autovalor

array([3., 1.])

In [6]:
autovetor

array([[1., 0.],
       [0., 1.]])

In [7]:
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[0], autovetor[0,0],autovetor[1][0]))
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[1], autovetor[0,1],autovetor[1][1]))

O autovalor 3.000 está associado aos autovetores 1.000 e 0.000
O autovalor 1.000 está associado aos autovetores 0.000 e 1.000


In [16]:
B = np.array([[4,-3],[2,-1]])
B

array([[ 4, -3],
       [ 2, -1]])

In [17]:
autovalor, autovetor = np.linalg.eig(B)

In [18]:
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[0], autovetor[0,0],autovetor[1][0]))
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[1], autovetor[0,1],autovetor[1][1]))

O autovalor 2.000 está associado aos autovetores 0.832 e 0.555
O autovalor 1.000 está associado aos autovetores 0.707 e 0.707


0.8325