In [48]:
import numpy as np

In [65]:
#multiplicando matrizes

# Demonstrando a multiplicação de matrizes manualmente

A = np.array([[2,2,3],[3,2,2]])
B = np.array([[1,2,3],[3,2,1],[2,0,1]])
print(A, "\n")
print(B)

resultado = []
for i in range(A.shape[0]):
    linha = []
    print("\n linha", i)
    for j in range(B.shape[0]):
        soma = 0
        print("coluna", j)
        for k in range(A.shape[1]):
            soma += A[i][k] * B[k][j]
        linha.append(soma)
    resultado.append(linha)

[[2 2 3]
 [3 2 2]] 

[[1 2 3]
 [3 2 1]
 [2 0 1]]

 linha 0
coluna 0
coluna 1
coluna 2

 linha 1
coluna 0
coluna 1
coluna 2


In [66]:
print(np.array(resultado))

[[14  8 11]
 [13 10 13]]


In [67]:
R = np.dot(A,B)
R

array([[14,  8, 11],
       [13, 10, 13]])

In [52]:
print(A.shape[0])

2
